# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculator.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'calculator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\"\"\n\nAddRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x1d\n\x0b\x41\x64\x64Response\x12\x0e\n\x06result\x18\x01 \x01(\x05\"\'\n\x0fSubtractRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\"\n\x10SubtractResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\"\'\n\x0fMultiplyRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\"\n\x10MultiplyResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\"%\n\rDivideRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\" \n\x0e\x44ivideResponse\x12\x0e\n\x06result\x18\x01 \x01(\x01\x32\xbb\x01\n\nCalculator\x12 \n\x03\x41\x64\x64\x12\x0b.AddRequest\x1a\x0c.AddResponse\x12/\n\x08Subtract\x12\x10.SubtractRequest\x1a\x11.SubtractResponse\x12/\n\x08Multiply\x12\x10.MultiplyRequest\x1a\x11.MultiplyResponse\x12)\n\x06\x44ivide\x12\x0e.DivideRequest\x1a\x0f.DivideResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDREQUEST']._serialized_start=20
  _globals['_ADDREQUEST']._serialized_end=54
  _globals['_ADDRESPONSE']._serialized_start=56
  _globals['_ADDRESPONSE']._serialized_end=85
  _globals['_SUBTRACTREQUEST']._serialized_start=87
  _globals['_SUBTRACTREQUEST']._serialized_end=126
  _globals['_SUBTRACTRESPONSE']._serialized_start=128
  _globals['_SUBTRACTRESPONSE']._serialized_end=162
  _globals['_MULTIPLYREQUEST']._serialized_start=164
  _globals['_MULTIPLYREQUEST']._serialized_end=203
  _globals['_MULTIPLYRESPONSE']._serialized_start=205
  _globals['_MULTIPLYRESPONSE']._serialized_end=239
  _globals['_DIVIDEREQUEST']._serialized_start=241
  _globals['_DIVIDEREQUEST']._serialized_end=278
  _globals['_DIVIDERESPONSE']._serialized_start=280
  _globals['_DIVIDERESPONSE']._serialized_end=312
  _globals['_CALCULATOR']._serialized_start=315
  _globals['_CALCULATOR']._serialized_end=502
# @@protoc_insertion_point(module_scope)
